apiVersion: v1
kind: Service
metadata:
  labels:
    app: echo
  name: echo
spec:
  ports:
    - name: http
      port: 8080
      protocol: "TCP"
  selector:
    app: echo
  type: LoadBalancer
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: echo
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: echo
      name: echo
    spec:
      containers:
        - name: echo
          image: "gcr.io/hightowerlabs/echo:1.0.0"
          imagePullPolicy: Always
          env:
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: /var/secrets/google/service-account.json
            - name: PROJECT_ID
              value: ""
            - name: TOPIC
              value: echo
          volumeMounts:
            - name: certs
              mountPath: /etc/ssl/certs
            - name: google-application-credentials
              mountPath: /var/secrets/google
      volumes:
        - name: certs
          hostPath:
            path: /etc/ssl/certs
        - name: google-application-credentials
          secret:
            secretName: echo
