steps:
  - name: "gcr.io/cloud-builders/go"
    env: ["PROJECT_ROOT=echo-challenge", "CGO_ENABLED=0"]
    args: ["build", "-o", "echo", "-tags", "netgo", "."]
    id: "go-build-echo"
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/${PROJECT_ID}/echo:1.0.0", "."]
    id: "docker-build"

images: ["gcr.io/${PROJECT_ID}/echo:1.0.0"]
