apiVersion: extensions/v1beta1
kind: ReplicaSet
metadata:
  name: echo
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: echo
      name: echo
    spec:
      containers:
        - name: echo
          image: "gcr.io/hightowerlabs/echo:1.0.0"
          env:
            - name: "PROJECT_ID"
              value: ""
            - name: "TOPIC"
              value: "echo"
          volumeMounts:
            - name: "certs"
              mountPath: "/etc/ssl/certs"
      volumes:
        - name: "certs"
          hostPath:
            path: "/etc/ssl/certs"
